baseurl: ''
url: 'https://qualitystandardohio.com'
title: 'Quality Standard Ohio'
telefono: "(614) 384-3087"
whatsapp: "+16143843087"
address: 2211 Dublin Rd Unit 467 Columbus, Ohio 43228
email: "support@qualitystandardoh.com"

markdown: kramdown

plugins:
  - jekyll-paginate

paginate: 8
paginate_path: "/blog/page:num/"

permalink: :slug
compress_html:
  clippings: []
  comments: []
  endings: []
  ignore:
  envs: []
  blanklines: false
  profile: false
  startings: []

collections:
  redirects:
    output: true
  specialized:
    output: true
    permalink: /specialized/:path
  commercial:
    output: true
    permalink: /commercial/:path
  residential:
    output: true
    permalink: /residential/:path
  areas:
    output: true
    permalink: /areas/:path
  posts:
    output: true
    permalink: /blog/:slug
  category:
    output: true
    permalink: /category/:name

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      schema: "BlogPosting"
