baseurl: '/quality'
url: 'https://qualitystandardohio.com/'
title: 'Quality Standard Ohio'
telefono: "(614) 602-5494"
whatsapp: "+16143843087"
email: "support@qualitystandardoh.com"
maps: https://maps.app.goo.gl/LAmA8gQZFBxwKak28

markdown: kramdown

permalink: :slug

compress_html:
  clippings: []
  comments: []
  endings: []
  ignore:
  envs: []
  blanklines: false
  profile: false
  startings: []

collections:
  specialized:
    output: true
    permalink: /specialized/:path
  commercial:
    output: true
    permalink: /commercial/:path
  residential:
    output: true
    permalink: /residential/:path
  posts:
    output: true
    permalink: /blog/:slug
