- title: "Doorstep Trash Pick up"
  description: "Experience dependable waste collection from designated spots within your apartment community, ensuring a cleaner living environment with every pickup."
  img: "img/cleaning.avif"
  alt: "/services/trash-pickup"
  title_img: Lorem ipsum
