# Residential cleaning services
residential_cleaning_services:
  - title: "Regular house cleaning"
    description: "We keep your home clean with regular services like dusting, mopping, and vacuuming. Perfect for busy families needing reliable home cleaning services near them."
    img: "img/service-regular-cleaning.avif"
    alt: "Girl cleaning an apartment in Columbus, service offered by Quality Standard Ohio"
    title_img: "Quality Standard Ohio Cleaning Apartment Service"
    url_service: "residential/regular"
    url_text: "Regular house cleaning Columbus"
  - title: "Deep cleaning"
    description: "Need a deeper household cleaning? We scrub every corner, removing built-up dirt and allergens for a fresh, healthy home."
    img: "img/deep-cleaning-quality-service.avif"
    alt: "Deep cleaning service in Columbus by Quality Standard Ohio"
    title_img: "Quality Standard Ohio Deep Cleaning Service"
    url_service: "residential/deep-cleaning"
    url_text: "Deep cleaning columbus ohio"
  - title: "Move in/out cleaning"
    description: "Make your move stress-free with our detailed cleaning for both old and new homes. Trust us for the move-out cleaning service and enjoy a spotless space."
    img: "img/service-move-cleaning.avif"
    alt: "Move in/out cleaning service in Columbus area by Quality Standard Ohio"
    title_img: "Quality Standard Ohio Move In/Out Cleaning Service"
    url_service: "residential/move-in-out"
    url_text: "Move in and out cleaning services"
  - title: "Apartment cleaning"
    description: "We offer tailored cleaning for apartments, ensuring a tidy, comfortable living space. Look no further than Quality Standard Ohio for residential cleaning services."
    img: "img/apartment-cleaning-quality-service.avif"
    alt: "Professional apartment cleaning service in Columbus by Quality Standard Ohio"
    title_img: "Quality Standard Ohio Apartment Cleaning Service"
    url_service: "residential/apartment"
    url_text: "Clean apartments service"
  - url: "residential-cleaning"

# Commercial cleaning services
commercial_cleaning_services:
  - title: "Office cleaning"
    description: "Keep your workspace spotless with our flexible office cleaning. We help businesses in Columbus maintain a professional appearance."
    img: "img/quality-service-office-cleaning.avif"
    alt: "Professional office cleaning service in Columbus by Quality Standard Ohio"
    title_img: "Quality Standard Ohio Office Cleaning Service"
    url_service: "residential/office-cleaning"
    url_text: "Office cleaning services in columbus oh"
  - title: "kitchen deep cleaning services"
    description: "Our medical cleaning service follows strict hygiene standards for clinics and medical offices, ensuring a safe environment with experts."
    img: "img/quality-service-medical-cleaning.avif"
    alt: "Medical facility cleaning service in Columbus by Quality Standard Ohio"
    title_img: "Quality Standard Ohio Medical Facility Cleaning Service"
    url_service: "residential/kitchen-cleaning"
    url_text: "Commercial kitchen cleaning columbus"
  - title: "Retail store cleaning"
    description: "A clean store attracts more customers. Our store cleaning service retail keeps floors, windows, and displays perfectly clean."
    img: "img/quality-service-retail-cleaning.avif"
    alt: "Retail cleaning service in Columbus by Quality Standard Ohio"
    title_img: "Quality Standard Ohio Retail Cleaning Service"
    url_service: "residential/retail"
    url_text: "Cleaning services for retail stores"
  - title: "Restaurants cleaning"
    description: "We handle both kitchen and dining area cleaning, helping restaurants meet health standards."
    img: "img/quality-service-restaurant-cleaning.avif"
    alt: "Restaurant cleaning service in Columbus by Quality Standard Ohio"
    title_img: "Quality Standard Ohio Restaurant Cleaning Service"
    url_service: "residential/restaurant"
    url_text: "Commercial kitchen cleaning columbus"
  - url: "commercial-cleaning"

# Specialized cleaning services
specialized_cleaning_services:
  - title: "Carpet cleaning"
    description: "Our deep carpet cleaning removes dirt, stains, and allergens, making your carpets look and feel fresh."
    img: "img/quality-service-carpet-cleaning.avif"
    alt: "Professional carpet cleaning service in Columbus by Quality Standard Ohio"
    title_img: "Quality Standard Ohio Carpet Cleaning Service"
    url_service: "residential/carpet-cleaning"
    url_text: "Carpet cleaners columbus ohio"
  - title: "Window cleaning"
    description: "Let more light in with streak-free window cleaning. We handle hard-to-reach windows for a clear, bright view."
    img: "img/quality-service-window-cleaning.avif"
    alt: "Window cleaning service in Columbus by Quality Standard Ohio"
    title_img: "Quality Standard Ohio Window Cleaning Service"
    url_service: "residential/window-cleaning"
    url_text: "Window cleaning columbus ohio"
  - title: "Power washing columbus"
    description: "We keep your pool clean and balanced so that you can enjoy it without the hassle. Choose our pool cleaning service for reliable care."
    img: "img/quality-service-pool-cleaning.avif"
    alt: "Pool maintenance service in Columbus by Quality Standard Ohio"
    title_img: "Quality Standard Ohio Pool Maintenance Service"
    url_service: "residential/pool-maintenance"
    url_text: "House power washing columbus ohio"
  - title: "Floor care"
    description: "We polish and clean all types of floors, extending their life and shine and providing a high-quality floor care service."
    img: "img/quality-service-floor-care.avif"
    alt: "Professional floor care service in Columbus by Quality Standard Ohio"
    title_img: "Quality Standard Ohio Floor Care Service"
    url_service: "residential/floor-care"
    url_text: "Floor care cleaning services"
  - url: "specialized-cleaning"